### ISSUE TITLE
TypeError: Unknown parameter type: <class 'theano.tensor.var.TensorVariable'>

### ISSUE THREAD

**Issue by Wonderdch** [feay1234/CARA#2]
Sorry to bother you after two years.😅
There is an error while i try to runing [colab](https://colab.research.google.com/drive/1yrLp016VNWLyatt1LlLW00pZwYVPf-M3) 
![image](https://user-images.githubusercontent.com/12708888/156136902-de9dbfa3-2e9b-4359-963d-48cd995476ac.png)
I have search the question, and find out the keras is already backend with Theano.
As a newbee for Theano, i couldn't find more ways to solve this problem, please take a look at if you have free time.

**Comment by feay1234** [comment]
Thank you very much for your feedback. I got the same error, there should be some bug related to dependencies in the Colab environment.  For some reason, Keras keeps using TensorFlow as backend, therefore, it may not recognise theano tensor variable. 

However, there is no error when I try to run this script on my local machine. 

Please check out this:
https://github.com/feay1234/CARA/blob/master/CARA%20on%20brightkite%20dataset.ipynb 

`pip install -r requirements.txt`
